info:
  contact: {}
  description: This is a volunteer service API
  title: Onboarding and Volunteer Service API
  version: "1.0"
paths: {}
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
